[project]
name = "shiqu-todo"
version = "2.0.0"
description = "一个轻量级全功能的待办清单软件。"
requires-python = ">=3.12"
dependencies = [
    "flet==0.28.3",
    "requests>=2.32.4",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
